import * as THREE from "https://cdn.jsdelivr.net/npm/three@0.179.1/build/three.module.js";
const $=id=>document.getElementById(id), app=$("app");
const renderer=new THREE.WebGLRenderer({canvas:$("scene"),antialias:true});
renderer.setPixelRatio(Math.min(2,devicePixelRatio||1));renderer.shadowMap.enabled=true;
const scene=new THREE.Scene(), camera=new THREE.PerspectiveCamera(45,1,.1,2500);
const hemi=new THREE.HemisphereLight(0xcfeaff,0x274533,1.5);scene.add(hemi);
const sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(-80,120,80);scene.add(sun);
scene.add(new THREE.AmbientLight(0x8ab6c8,.28));
const MODES={day:{sky:0x77b8df,water:0x1d6289,hemi:1.5,sun:2},sunset:{sky:0xe58d61,water:0x245b79,hemi:1,sun:2.6},night:{sky:0x07182f,water:0x071f35,hemi:.25,sun:.25}};
const WX={tss:["Partly Cloudy",10,"NE 12 kn","Slight"],headon:["Clear",12,"ENE 8 kn","Slight"],crossing:["Partly Cloudy",10,"NE 12 kn","Slight"],standon:["Partly Cloudy",10,"NE 12 kn","Slight"],overtaking:["Clear",12,"ENE 8 kn","Slight"],restricted:["Haze",2,"SE 7 kn","Moderate"]};
const SCALE=4,WORLD=1.55,DUR=180;
let running=false,paused=false,last=0,startT=0,score=1000,modeKey="day",scenarioKey="tss",radarRange=3,targetIndex=0,cameraMode=0,msgTimer=0;
let player={x:0,z:0,yaw:0,speed:13,targetSpeed:13,rudder:0,targetRudder:0,rot:0,roll:0,pitch:0,heave:0};
let traffic=[],water,ownShip,ownWake=[],foam,selectedRing,joyActive=false,joyPointer=null,chaseYaw=0,chaseAnchor=new THREE.Vector3(),chaseInit=false;
const mat=(c,r=.55)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:.08});
const box=(w,h,d,c)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));m.castShadow=true;return m};
const cyl=(r,h,c)=>{const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,14),mat(c));m.castShadow=true;return m};
function hull(L,B,c){const g=new THREE.Group();const b=box(B,1.1,L*.78,c);b.position.z=L*.05;g.add(b);const bow=new THREE.Mesh(new THREE.ConeGeometry(B*.58,L*.24,4),mat(c));bow.rotation.x=Math.PI/2;bow.rotation.z=Math.PI/4;bow.position.z=-L*.45;g.add(bow);return g}
function ship(type,own=false){const g=new THREE.Group();let L=13,B=3.5,c=0x315e59;if(type==="Container Ship"){L=17;B=4.2;c=0x155ea1}if(type==="LNG Carrier"){L=15;B=4.4;c=0x176a51}if(type.includes("Tanker")){L=15.5;B=4.3;c=0x3b3033}if(type==="Bulk Carrier"){L=14;B=4;c=0x8b4a2c}if(type==="Fast Ferry"){L=8.5;B=2.7;c=0xe7ecef}g.add(hull(L,B,c));const deck=box(B*.78,.25,L*.56,0x8f9ca0);deck.position.y=.72;g.add(deck);if(type==="Container Ship"){const cs=[0xe85e48,0xe9b845,0x3b82c4,0x56a968];for(let i=0;i<6;i++)for(let j=-1;j<=1;j++){const q=box(.9,.7,1.2,cs[(i+j+4)%4]);q.position.set(j,1.25,-4+i*1.5);g.add(q)}}else if(type==="LNG Carrier"){for(let i=0;i<4;i++){const s=new THREE.Mesh(new THREE.SphereGeometry(1.45,16,10),mat(0xf0efdc));s.scale.y=.65;s.position.set(0,1.55,-4.2+i*2.7);g.add(s)}}else if(type.includes("Tanker")){for(let i=0;i<5;i++){const p=cyl(.1,B*.62,0xc0c8c9);p.rotation.z=Math.PI/2;p.position.set(0,1.25,-4.5+i*2.1);g.add(p)}}else if(type==="Bulk Carrier"){for(let i=0;i<4;i++){const h=box(B*.68,.3,1.7,0x39291f);h.position.set(0,1.2,-4.2+i*2.6);g.add(h)}}else if(type==="Fast Ferry"){const h=box(B*.9,2.1,L*.58,0xf5f6f7);h.position.y=1.7;g.add(h)}const br=box(B*.7,2.3,2,0xf1f3ef);br.position.set(0,1.9,L*.31);g.add(br);const mast=cyl(.06,3,0xe5ecee);mast.position.set(0,3.2,L*.2);g.add(mast);g.userData={L,B};if(own)g.scale.set(2.35,2.35,2.35);return g}
function makeScene(){const geo=new THREE.PlaneGeometry(900,1300,40,60);geo.rotateX(-Math.PI/2);water=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:MODES.day.water,roughness:.35,metalness:.18}));scene.add(water);for(let z=-900;z<100;z+=22){for(const x of[-17,17]){const s=box(.24,.05,10,0x65dff2);s.position.set(x,.12,z);scene.add(s)}if(z%44===0)for(const x of[-25,25]){const b=cyl(.7,2.5,x<0?0xd63c3c:0x2ca85a);b.position.set(x,1.25,z);scene.add(b)}}for(const [x,z,r,h] of[[-120,-190,65,20],[100,-220,85,25],[-170,-360,100,30],[150,-420,125,36]]){const g=new THREE.Group();for(let i=0;i<8;i++){const q=new THREE.Mesh(new THREE.ConeGeometry(r*(.24+Math.random()*.28),h*(.6+Math.random()*.7),7),mat(0x245d3f));q.position.set((Math.random()-.5)*r,h*.4,(Math.random()-.5)*r*.7);g.add(q)}g.position.set(x,0,z);scene.add(g)}ownShip=ship("Product Tanker",true);scene.add(ownShip);const wm=new THREE.MeshBasicMaterial({color:0xecfbff,transparent:true,opacity:.24,depthWrite:false,side:THREE.DoubleSide});for(let i=0;i<18;i++){const w=new THREE.Mesh(new THREE.PlaneGeometry(2+i*.25,5.5),wm.clone());w.rotation.x=-Math.PI/2;scene.add(w);ownWake.push(w)}const pos=[];for(let i=0;i<480;i++)pos.push((Math.random()-.5)*125,.12,(Math.random()-.5)*900);const fg=new THREE.BufferGeometry();fg.setAttribute("position",new THREE.Float32BufferAttribute(pos,3));foam=new THREE.Points(fg,new THREE.PointsMaterial({color:0xe7f9ff,size:.28,transparent:true,opacity:.32,depthWrite:false}));scene.add(foam);selectedRing=new THREE.Mesh(new THREE.TorusGeometry(5,.18,8,32),new THREE.MeshBasicMaterial({color:0xffd057}));selectedRing.rotation.x=Math.PI/2;scene.add(selectedRing)}
function addTraffic(name,type,x,z,yaw,speed){const m=ship(type);m.position.set(x,.3,z);m.rotation.y=yaw;scene.add(m);traffic.push({name,type,x,z,yaw,speed,mesh:m})}
function clearTraffic(){traffic.forEach(t=>scene.remove(t.mesh));traffic=[]}
function loadScenario(){clearTraffic();scenarioKey=$("scenario").value;player.x=player.z=0;player.yaw=0;player.speed=player.targetSpeed=13;player.rudder=player.targetRudder=player.rot=0;targetIndex=0;if(scenarioKey==="headon"){addTraffic("EASTERN RESOLVE","Container Ship",0,-115,Math.PI,14);addTraffic("COASTAL TRADER","Bulk Carrier",22,-230,0,10)}else if(scenarioKey==="crossing"){addTraffic("STARBOARD CROSSER","Product Tanker",42,-92,-Math.PI/2,14);addTraffic("DISTANT BOX","Container Ship",-14,-250,0,15)}else if(scenarioKey==="standon"){addTraffic("PORT CROSSER","Container Ship",-42,-92,Math.PI/2,15);addTraffic("FOLLOWING TANKER","Product Tanker",14,-220,0,12)}else if(scenarioKey==="overtaking"){addTraffic("SLOW MERCHANT","Bulk Carrier",0,-78,0,7);addTraffic("OUTER LANE","Container Ship",18,-210,0,14)}else if(scenarioKey==="restricted"){addTraffic("RADAR TARGET A","Crude Tanker",11,-92,Math.PI,11);addTraffic("RADAR TARGET B","Container Ship",-18,-138,0,13);addTraffic("FERRY ECHO","Fast Ferry",36,-72,-Math.PI/2,22)}else{addTraffic("OCEANIC LION","Container Ship",-18,-145,0,15);addTraffic("GAS HARMONY","LNG Carrier",20,-125,Math.PI,16);addTraffic("SEA HARMONY","Crude Tanker",-6,-92,Math.PI,12);addTraffic("MINERAL DAWN","Bulk Carrier",16,-205,0,11);addTraffic("LION CITY EXPRESS","Fast Ferry",46,-72,-Math.PI/2,25)}const w=WX[scenarioKey];$("weather").textContent=w[0];$("visibility").textContent=w[1]+" NM";$("wind").textContent=w[2];$("sea").textContent=w[3];$("scenarioStatus").textContent="Active";scene.fog=new THREE.FogExp2(scenarioKey==="restricted"?0xb2bcc0:0x91adba,scenarioKey==="restricted"?.012:.0038);lockShipView()}
function vel(yaw,speed){return{x:Math.sin(yaw)*speed*.18,z:-Math.cos(yaw)*speed*.18}}
function cpaData(t){const rx=t.x-player.x,rz=t.z-player.z,tv=vel(t.yaw,t.speed),pv=vel(player.yaw,player.speed),vx=tv.x-pv.x,vz=tv.z-pv.z,vv=vx*vx+vz*vz;let tm=vv?-(rx*vx+rz*vz)/vv:0;if(tm<0)tm=0;return{range:Math.hypot(rx,rz)/18,cpa:Math.hypot(rx+vx*tm,rz+vz*tm)/18,tcpa:tm/60}}
function encounter(t){if(!t)return{rule:"Rule 10",role:"TSS vessel",text:"Proceed in the appropriate traffic lane."};if(scenarioKey==="restricted")return{rule:"Rule 19",role:"Restricted visibility",text:"Use radar systematically, proceed at safe speed and take early avoiding action."};const dx=t.x-player.x,dz=t.z-player.z,rel=(Math.atan2(dx,-dz)*180/Math.PI+360)%360,diff=Math.abs((((t.yaw-player.yaw)*180/Math.PI+540)%360)-180);if(diff<35&&dz<0&&player.speed>t.speed+1)return{rule:"Rule 13",role:"Give-way",text:"Overtaking vessel must keep out of the way until finally past and clear."};if(diff>145&&(rel<25||rel>335))return{rule:"Rule 14",role:"Both give-way",text:"Alter course to starboard for a port-to-port passing."};if(rel>15&&rel<112.5)return{rule:"Rules 15/16",role:"Give-way",text:"Take early and substantial action; avoid crossing ahead."};if(rel>247.5&&rel<345)return{rule:"Rule 17",role:"Stand-on",text:"Initially keep course and speed while monitoring the give-way vessel."};return{rule:"Rules 5/7/8",role:"Assess",text:"Maintain lookout, determine collision risk and make an early positive manoeuvre."}}
function selected(){return traffic[targetIndex]||null}
function setHelm(v){if(!running||paused)return;player.targetRudder=v;setJoy(v/20);$("port").classList.toggle("active",v<0);$("mid").classList.toggle("active",v===0);$("stbd").classList.toggle("active",v>0);show(v<0?`PORT ${Math.abs(v)}° — turn starting`:v>0?`STARBOARD ${v}° — turn starting`:"MIDSHIPS — checking swing")}
function setSpeed(v,btn){if(!running||paused)return;player.targetSpeed=v;document.querySelectorAll("[data-speed]").forEach(b=>b.classList.remove("active"));if(btn)btn.classList.add("active");$("engineOrder").textContent=v<0?(v<=-8?"FULL ASTERN":v<=-5?"HALF ASTERN":"SLOW ASTERN"):v===0?"STOP":v>=18?"FULL AHEAD":v>=13?"HALF AHEAD":"SLOW AHEAD";show("ENGINE ORDER · "+$("engineOrder").textContent)}
function update(dt,t){const rate=player.targetSpeed<player.speed?.55:.38;player.speed=move(player.speed,player.targetSpeed,rate*SCALE*dt);player.rudder=move(player.rudder,player.targetRudder,3.2*SCALE*dt);const sign=player.speed<-.1?-1:1,desired=-(player.rudder/20)*THREE.MathUtils.degToRad(.27)*THREE.MathUtils.clamp(Math.abs(player.speed)/13,.08,1.4)*sign*SCALE;player.rot=lerpExp(player.rot,desired,dt,1.5);player.rot=THREE.MathUtils.clamp(player.rot,-THREE.MathUtils.degToRad(.9),THREE.MathUtils.degToRad(.9));player.yaw+=player.rot*dt;const p=vel(player.yaw,player.speed);player.x+=p.x*dt*WORLD;player.z+=p.z*dt*WORLD;player.heave=lerpExp(player.heave,Math.sin(t*.00075)*.12,dt,1.3);player.roll=lerpExp(player.roll,-player.rudder/20*.07,dt,1.8);player.pitch=lerpExp(player.pitch,Math.sin(t*.00062)*.008,dt,2.2);ownShip.position.set(player.x,.5+player.heave,player.z);ownShip.rotation.set(player.pitch,player.yaw,player.roll);traffic.forEach(o=>{const v=vel(o.yaw,o.speed);o.x+=v.x*dt*WORLD;o.z+=v.z*dt*WORLD;o.mesh.position.set(o.x,.3+Math.sin(t*.0007+o.x)*.08,o.z);o.mesh.rotation.y=o.yaw;if(o.z-player.z>160||o.z-player.z<-700){o.z=player.z-250-Math.random()*350;o.x=player.x-35+Math.random()*70}});updateWake();updateWater(t);updateCamera(dt);updateHud();drawRadar();drawMap()}
function move(c,t,s){return c<t?Math.min(t,c+s):c>t?Math.max(t,c-s):c}function lerpExp(c,t,dt,tau){return THREE.MathUtils.lerp(c,t,1-Math.exp(-dt/tau))}
function updateWake(){const pwr=THREE.MathUtils.clamp(Math.abs(player.speed)/18,0,1),sgn=player.speed<-.1?-1:1;ownWake.forEach((w,i)=>{w.position.set(player.x+Math.cos(player.yaw)*Math.sin(i*.35)*(.6+i*.05),.08,player.z+Math.cos(player.yaw)*(7+i*4.8)*sgn);w.rotation.x=-Math.PI/2;w.rotation.z=-player.yaw;w.material.opacity=(.04+pwr*.28)*(1-i/22)});const a=foam.geometry.attributes.position;for(let i=0;i<a.count;i++){let z=a.getZ(i)+player.speed*.42;if(z>450)z=-450;if(z<-450)z=450;a.setZ(i,z)}a.needsUpdate=true;foam.position.set(player.x,0,player.z-200);foam.rotation.y=player.yaw;foam.material.opacity=.1+pwr*.35}
let waterFrame=0;function updateWater(t){const a=water.geometry.attributes.position;for(let i=0;i<a.count;i++){const x=a.getX(i),z=a.getZ(i);a.setY(i,Math.sin(x*.04+z*.012+t*.0011)*.28+Math.cos(z*.027+t*.0008)*.16)}a.needsUpdate=true;if((waterFrame++%5)===0)water.geometry.computeVertexNormals();water.position.set(player.x,0,player.z-400)}
function lockShipView(){cameraMode=0;chaseYaw=player.yaw;chaseAnchor.set(player.x,0,player.z);chaseInit=true;camera.position.set(player.x,19,player.z+38);show("OWN SHIP VIEW")}
function updateCamera(dt){if(!chaseInit)lockShipView();if(cameraMode===0){const ye=norm(player.yaw-chaseYaw);chaseYaw+=ye*(1-Math.exp(-dt*.42));chaseAnchor.lerp(new THREE.Vector3(player.x,0,player.z),1-Math.exp(-dt*.8));const back=38,lat=THREE.MathUtils.clamp(ye*34,-8,8),pos=new THREE.Vector3(chaseAnchor.x+Math.sin(chaseYaw)*-back+Math.cos(chaseYaw)*lat,19,chaseAnchor.z+Math.cos(chaseYaw)*back-Math.sin(chaseYaw)*lat);camera.position.lerp(pos,1-Math.exp(-dt*2));camera.lookAt(player.x+Math.sin(player.yaw)*3,2,player.z-Math.cos(player.yaw)*3)}else if(cameraMode===1){camera.position.lerp(new THREE.Vector3(player.x,8.4,player.z+2),1-Math.exp(-dt*2));camera.lookAt(player.x+Math.sin(player.yaw)*90,5,player.z-Math.cos(player.yaw)*90)}else{camera.position.lerp(new THREE.Vector3(player.x+55,70,player.z+60),1-Math.exp(-dt*1.7));camera.lookAt(player.x,0,player.z-70)}}
function norm(a){while(a>Math.PI)a-=Math.PI*2;while(a<-Math.PI)a+=Math.PI*2;return a}function heading(){return(Math.round(90-THREE.MathUtils.radToDeg(player.yaw)+360)%360)}
function updateHud(){const dir=player.speed>.08?"AHEAD":player.speed<-.08?"ASTERN":"STOPPED";$("actualSpeed").textContent=Math.abs(player.speed).toFixed(1)+" kn "+dir;$("heading").textContent=String(heading()).padStart(3,"0")+"°";$("rudder").textContent=(player.rudder<0?Math.abs(player.rudder).toFixed(0)+"° P":player.rudder>0?player.rudder.toFixed(0)+"° S":"0°");$("motionText").textContent=(player.rudder<-1?Math.abs(player.rudder).toFixed(0)+"° PORT":player.rudder>1?player.rudder.toFixed(0)+"° STARBOARD":"MIDSHIPS")+" · "+(Math.abs(player.rot)>THREE.MathUtils.degToRad(.03)?"SWINGING":"STEADY");$("score").textContent=Math.round(score);const t=selected();if(!t)return;const d=cpaData(t),e=encounter(t);$("targetName").textContent=t.name;$("targetType").textContent=t.type;$("range").textContent=d.range.toFixed(2)+" NM";$("cpa").textContent=d.cpa.toFixed(2)+" NM";$("tcpa").textContent=d.tcpa.toFixed(1)+" min";const rk=d.cpa<.3?"HIGH":d.cpa<.7?"CAUTION":"LOW";$("risk").textContent=rk;$("risk").className=rk==="HIGH"?"high":rk==="CAUTION"?"caution":"ok";$("colreg").innerHTML=`<b>${e.rule} · ${e.role}</b><br>${e.text}`;$("arpa").textContent=`${t.name} · R ${d.range.toFixed(2)} · CPA ${d.cpa.toFixed(2)} · TCPA ${d.tcpa.toFixed(1)} min`;selectedRing.position.set(t.x,.2,t.z)}
function drawRadar(){const c=$("radar"),x=c.getContext("2d"),W=c.width,H=c.height,cx=W/2,cy=H/2,R=Math.min(W,H)*.42;x.clearRect(0,0,W,H);x.fillStyle="#031018";x.fillRect(0,0,W,H);x.strokeStyle="#59d86a44";[.25,.5,.75,1].forEach(k=>{x.beginPath();x.arc(cx,cy,R*k,0,Math.PI*2);x.stroke()});x.beginPath();x.moveTo(cx-R,cy);x.lineTo(cx+R,cy);x.moveTo(cx,cy-R);x.lineTo(cx,cy+R);x.stroke();x.fillStyle="#74e77c";x.beginPath();x.moveTo(cx,cy-8);x.lineTo(cx-5,cy+7);x.lineTo(cx+5,cy+7);x.closePath();x.fill();const wr=radarRange*18;traffic.forEach((t,i)=>{const dx=t.x-player.x,dz=t.z-player.z;if(Math.hypot(dx,dz)>wr)return;const px=cx+dx/wr*R,py=cy+dz/wr*R;x.fillStyle=i===targetIndex?"#ffd04f":"#75e78a";x.beginPath();x.arc(px,py,i===targetIndex?4:3,0,Math.PI*2);x.fill();if(i===targetIndex){x.strokeStyle="#ffd04f";x.strokeRect(px-7,py-7,14,14);x.setLineDash([3,3]);x.beginPath();x.moveTo(cx,cy);x.lineTo(px,py);x.stroke();x.setLineDash([])}})}
function drawMap(){const c=$("map"),x=c.getContext("2d"),W=c.width,H=c.height;x.clearRect(0,0,W,H);x.fillStyle="#dfe7e7";x.fillRect(0,0,W,H);x.fillStyle="#eef3ef";x.strokeStyle="#111";x.lineWidth=2;x.beginPath();x.moveTo(0,12);x.lineTo(80,20);x.lineTo(120,52);x.lineTo(176,28);x.lineTo(W,18);x.lineTo(W,0);x.lineTo(0,0);x.closePath();x.fill();x.stroke();x.beginPath();x.moveTo(0,H);x.lineTo(72,150);x.lineTo(132,158);x.lineTo(180,130);x.lineTo(W,145);x.lineTo(W,H);x.closePath();x.fill();x.stroke();x.strokeStyle="#168237";x.lineWidth=3;x.beginPath();x.moveTo(15,132);x.lineTo(282,65);x.stroke();x.strokeStyle="#15378f";x.beginPath();x.moveTo(20,157);x.lineTo(287,91);x.stroke();x.fillStyle="#5d6470";x.font="9px system-ui";x.fillText("WESTBOUND",220,50);x.fillText("EASTBOUND",20,174);x.fillText("TSS / Singapore Strait training schematic",70,184);const mapPos=(wx,wz)=>({x:35+THREE.MathUtils.clamp((-wz)/650,0,1)*230+THREE.MathUtils.clamp(wx/60,-1,1)*15,y:148-THREE.MathUtils.clamp((-wz)/650,0,1)*75});const p=mapPos(player.x,player.z);x.fillStyle="#00bfe8";x.beginPath();x.arc(p.x,p.y,5,0,Math.PI*2);x.fill();traffic.slice(0,12).forEach(t=>{const p=mapPos(t.x,t.z);x.fillStyle="#e74b45";x.fillRect(p.x-2,p.y-3,4,6)})}
function setMode(k){modeKey=k;const m=MODES[k];scene.background=new THREE.Color(m.sky);water.material.color.set(m.water);hemi.intensity=m.hemi;sun.intensity=m.sun;$("mode").textContent=k.toUpperCase();document.querySelectorAll("[data-mode]").forEach(b=>b.classList.toggle("active",b.dataset.mode===k))}
function show(t){const m=$("message");m.textContent=t;m.classList.add("show");clearTimeout(msgTimer);msgTimer=setTimeout(()=>m.classList.remove("show"),1500)}
function horn(){if(!window.AudioContext&&!window.webkitAudioContext){show("Audio unavailable");return}const A=window.AudioContext||window.webkitAudioContext,a=new A(),g=a.createGain(),f=a.createBiquadFilter();f.type="lowpass";f.frequency.value=650;g.gain.setValueAtTime(.0001,a.currentTime);g.gain.exponentialRampToValueAtTime(.16,a.currentTime+.12);g.gain.setValueAtTime(.16,a.currentTime+1.3);g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+2.4);f.connect(g).connect(a.destination);[82,123,164].forEach((hz,i)=>{const o=a.createOscillator();o.type=i===0?"sawtooth":"sine";o.frequency.value=hz;o.connect(f);o.start();o.stop(a.currentTime+2.5)});show("SHIP WHISTLE · PROLONGED BLAST")}
function vhf(){const t=selected(),txt=t?`${t.name}, Fathom training vessel. Confirm your intentions. Collision risk will be managed in accordance with COLREGs.`:"Singapore VTS, Fathom training vessel eastbound in the traffic lane.";$("vhfText").textContent=txt;$("vhfPopup").classList.add("show");setTimeout(()=>$("vhfPopup").classList.remove("show"),3000);if("speechSynthesis"in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(txt);u.rate=1;speechSynthesis.speak(u)}}
function assess(){const t=selected();if(!t)return;const e=encounter(t),d=cpaData(t);show(`${e.rule} · ${e.role} · CPA ${d.cpa.toFixed(2)} NM`);score+=5}
function resize(){const w=app.clientWidth,h=app.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}addEventListener("resize",resize);
function start(){loadScenario();running=true;paused=false;startT=performance.now();last=0;$("startOverlay").style.display="none";app.focus()}
function frame(t){if(!last)last=t;const dt=Math.min(.05,(t-last)/1000);last=t;if(running&&!paused){update(dt,t);const rem=Math.max(0,DUR-(t-startT)/1000);$("time").textContent=String(Math.floor(rem/60)).padStart(2,"0")+":"+String(Math.floor(rem%60)).padStart(2,"0")}else{updateWater(t);updateCamera(dt);drawRadar();drawMap()}renderer.render(scene,camera);requestAnimationFrame(frame)}
function setJoy(nx){const base=$("joyBase"),knob=$("joyKnob"),max=base.clientWidth*.32;knob.style.transform=`translate(calc(-50% + ${nx*max}px),-50%)`;$("joyReadout").textContent=nx<-.05?Math.abs(Math.round(nx*20))+"° PORT":nx>.05?Math.round(nx*20)+"° STBD":"0° MIDSHIPS"}
function joyMove(e){if(!joyActive||e.pointerId!==joyPointer)return;const r=$("joyBase").getBoundingClientRect(),nx=THREE.MathUtils.clamp((e.clientX-(r.left+r.width/2))/(r.width*.32),-1,1);setHelm(Math.abs(nx)<.08?0:nx*20)}
$("joyBase").addEventListener("pointerdown",e=>{if(!running)return;joyActive=true;joyPointer=e.pointerId;$("joyBase").setPointerCapture?.(e.pointerId);joyMove(e)});$("joyBase").addEventListener("pointermove",joyMove);$("joyBase").addEventListener("pointerup",e=>{joyActive=false;joyPointer=null;show("HELM ORDER LATCHED · use MIDSHIPS to centre")});
$("port").onclick=()=>setHelm(-20);$("mid").onclick=()=>setHelm(0);$("stbd").onclick=()=>setHelm(20);document.querySelectorAll("[data-speed]").forEach(b=>b.onclick=()=>setSpeed(Number(b.dataset.speed),b));$("start").onclick=start;$("scenario").onchange=()=>{if(running)loadScenario()};$("prevTarget").onclick=()=>{targetIndex=(targetIndex-1+traffic.length)%traffic.length};$("nextTarget").onclick=()=>{targetIndex=(targetIndex+1)%traffic.length};$("shipView").onclick=lockShipView;$("camera").onclick=()=>{cameraMode=(cameraMode+1)%3;if(cameraMode===0)lockShipView();else show(cameraMode===1?"BRIDGE VIEW":"OVERVIEW VIEW")};$("radarRangeBtn").onclick=()=>{radarRange=radarRange===3?6:radarRange===6?12:3;$("radarRange").textContent=radarRange+" NM"};$("assess").onclick=assess;$("horn").onclick=horn;$("vhf").onclick=vhf;$("pause").onclick=()=>{paused=!paused;$("pause").textContent=paused?"RESUME":"PAUSE"};document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
app.addEventListener("keydown",e=>{if(e.key==="ArrowLeft")setHelm(-20);if(e.key==="ArrowRight")setHelm(20);if(e.key==="ArrowUp")setSpeed(18,document.querySelector('[data-speed="18"]'));if(e.key==="ArrowDown")setSpeed(8,document.querySelector('[data-speed="8"]'));if(e.key==="x")setSpeed(0,document.querySelector('[data-speed="0"]'));if(e.key==="z")setSpeed(-3,document.querySelector('[data-speed="-3"]'));if(e.code==="Space"){e.preventDefault();assess()}});
try{makeScene();resize();setMode("day");loadScenario();lockShipView();requestAnimationFrame(frame)}catch(err){$("error").style.display="block";$("error").textContent="3D game initialization failed: "+err.message;console.error(err)}